name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: shaheenn0  # وضعنا اسم حسابك هنا مباشرة لحل المشكلة
        password: ${{ secrets.DOCKER_PAT }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: shaheenn0/y-shaheen:latest
        
